variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 10
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_TAG: v2

# Building
arm_hitachi_cyclonev_defconfig:
  stage: build
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:build-$DOCKER_IMAGE_TAG
  variables:
    BUILD_ARCH: arm
    CONFIG: hitachi_cyclonev_defconfig
    CONFIG_LOC: cip-kernel-config
    BUILD_ONLY: "true"
  script:
    - /opt/build_kernel.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output

arm_hitachi_omap_defconfig:
  stage: build
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:build-$DOCKER_IMAGE_TAG
  variables:
    BUILD_ARCH: arm
    CONFIG: hitachi_omap_defconfig
    CONFIG_LOC: cip-kernel-config
    BUILD_ONLY: "true"
  script:
    - /opt/build_kernel.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output

arm_moxa_mxc_defconfig:
  stage: build
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:build-$DOCKER_IMAGE_TAG
  variables:
    BUILD_ARCH: arm
    CONFIG: moxa_mxc_defconfig
    CONFIG_LOC: cip-kernel-config
    BUILD_ONLY: "true"
  script:
    - /opt/build_kernel.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output

arm_renesas_shmobile_defconfig:
  stage: build
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:build-$DOCKER_IMAGE_TAG
  variables:
    BUILD_ARCH: arm
    CONFIG: renesas_shmobile_defconfig
    CONFIG_LOC: cip-kernel-config
    DEVICES: r8a7743-iwg20d-q7 r8a7745-iwg22d-sodimm
    DTBS: r8a7743-iwg20d-q7-dbcm-ca.dtb r8a7745-iwg22d-sodimm-dbhd-ca.dtb
  script:
    - /opt/build_kernel.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output

arm_siemens_imx6.config:
  stage: build
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:build-$DOCKER_IMAGE_TAG
  variables:
    BUILD_ARCH: arm
    CONFIG: siemens_imx6.config
    CONFIG_LOC: cip-kernel-config
    BUILD_ONLY: "true"
  script:
    - /opt/build_kernel.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output

arm64_moxa_eds_defconfig:
  stage: build
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:build-$DOCKER_IMAGE_TAG
  variables:
    BUILD_ARCH: arm64
    CONFIG: moxa_eds_defconfig
    CONFIG_LOC: cip-kernel-config
    BUILD_ONLY: "true"
  script:
    - /opt/build_kernel.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output

arm64_renesas_defconfig:
  stage: build
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:build-$DOCKER_IMAGE_TAG
  variables:
    BUILD_ARCH: arm64
    CONFIG: renesas_defconfig
    CONFIG_LOC: cip-kernel-config
    DEVICES: r8a774c0-ek874 r8a774a1-hihope-rzg2m-ex
    DTBS: r8a774c0-ek874.dtb r8a774a1-hihope-rzg2m-ex.dtb
  script:
    - /opt/build_kernel.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output

x86_plathome_obsvx2.config:
  stage: build
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:build-$DOCKER_IMAGE_TAG
  variables:
    BUILD_ARCH: x86
    CONFIG: plathome_obsvx2.config
    CONFIG_LOC: cip-kernel-config
    BUILD_ONLY: "true"
  script:
    - /opt/build_kernel.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output

x86_siemens_iot2000.config:
  stage: build
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:build-$DOCKER_IMAGE_TAG
  variables:
    BUILD_ARCH: x86
    CONFIG: siemens_iot2000.config
    CONFIG_LOC: cip-kernel-config
    BUILD_ONLY: "true"
  script:
    - /opt/build_kernel.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output

x86_siemens_server_defconfig:
  stage: build
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:build-$DOCKER_IMAGE_TAG
  variables:
    BUILD_ARCH: x86
    CONFIG: siemens_server_defconfig
    CONFIG_LOC: cip-kernel-config
    BUILD_ONLY: "true"
  script:
    - /opt/build_kernel.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output

x86_toshiba_atom_baytrail_cip.config:
  stage: build
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:build-$DOCKER_IMAGE_TAG
  variables:
    BUILD_ARCH: x86
    CONFIG: toshiba_atom_baytrail_cip.config
    CONFIG_LOC: cip-kernel-config
    BUILD_ONLY: "true"
  script:
    - /opt/build_kernel.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output

# Extra build configurations
arm_shmobile_defconfig:
  stage: build
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:build-$DOCKER_IMAGE_TAG
  variables:
    BUILD_ARCH: arm
    CONFIG: shmobile_defconfig
    CONFIG_LOC: intree
    DEVICES: r8a7743-iwg20d-q7 r8a7745-iwg22d-sodimm
    DTBS: r8a7743-iwg20d-q7-dbcm-ca.dtb r8a7745-iwg22d-sodimm-dbhd-ca.dtb
  script:
    - /opt/build_kernel.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output

arm64_defconfig:
  stage: build
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:build-$DOCKER_IMAGE_TAG
  variables:
    BUILD_ARCH: arm64
    CONFIG: defconfig
    CONFIG_LOC: intree
    DEVICES: r8a774c0-ek874 r8a774a1-hihope-rzg2m-ex
    DTBS: r8a774c0-ek874.dtb r8a774a1-hihope-rzg2m-ex.dtb
  script:
    - /opt/build_kernel.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output

# Testing
run_tests:
  stage: test
  image: registry.gitlab.com/cip-project/cip-testing/linux-cip-ci:test-$DOCKER_IMAGE_TAG
  when: always
  variables:
    GIT_STRATEGY: none
    TEST_TIMEOUT: 60
  script:
    - /opt/submit_tests.sh
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - output
